### ISSUE TITLE
Text outside of task card 

### ISSUE THREAD

**Issue by vkozloff** [ReproNim/brainverse#188] opened 2018-03-28 23:40 UTC
Some of the text from a task card appears outside of it

<img width="124" alt="screen shot 2018-03-28 at 7 39 42 pm" src="https://user-images.githubusercontent.com/29068838/38062016-d87a6ff2-32bf-11e8-87d0-6a5e88d12090.png">

**Comment by smpadhy** [comment] 2018-04-09 14:41
duplicate of #185

**Closed as completed by smpadhy** 2018-04-09 14:41 UTC
