### ISSUE TITLE
Saving an instrument

### ISSUE THREAD

**Issue by vkozloff** [ReproNim/brainverse#141] opened 2018-02-06 20:47 UTC
I don't see my instrument on github after selecting "Local Save and Push to GitHub."

**Comment by smpadhy** [comment] 2018-02-12 18:24
I am not able to reproduce this behaviour. @vkozloff if you still see this behaviour with new release (v0.0.3), let me know

**Comment by smpadhy** [comment] 2018-03-23 16:09
A fix has been added to 0.0.4-alpha version.

**Closed as completed by smpadhy** 2018-03-23 16:09 UTC
Labels: bug, Critical, instrumenteditor
